"""added is_active to token

Revision ID: 750e1d6f024b
Revises: c844ff941c60
Create Date: 2025-03-05 01:49:18.418610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '750e1d6f024b'
down_revision = 'c844ff941c60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'is_active')
    # ### end Alembic commands ###
